version: '3.7'

networks:
  backend:

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src
      - ./nodemon.json:/usr/nodemon.json
    container_name: server
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/diary
    expose:
      - '4000'
    ports:
      - '4000:4000'
    depends_on:
      # - mongodb
      - db
    networks:
      - backend
    command: bash -c "
      (while ! curl --output /dev/null --silent 'http://localhost:4000'; do sleep 1; done
      && npm run migrate:up)
      & npm run dev
      && fg"

  db:
    image: mongo:4
    volumes:
      - mongo:/data/mongo
    networks:
      - backend
  
  mongo-express:
    image: mongo-express
    restart: "no"
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    ports:
      - "3377:8081"
    networks:
      - backend

volumes:
  mongo:
    driver: local
    driver_opts:
      type: none
      device: $PWD/.data/mongo
      o: bind